server:
  port: 8080

spring:
  application:
    name: rabbitMq
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    template:
      default-receive-queue: student
